version: '3'
services:
  movies-front:
    # completa esta seccion, lee el archivo README en la carpeta movies-front 
    container_name: movies-front
    environment:
      - REACT_PORT
      - REACT_APP_API_URI
    
    volumes:
      - ./movies-front:/usr/app
      - /usr/app/node_modules

    command: -npm start 
    depends_on: 
    # de que servicio depende el frontend?
      - movies-api 
   
  movies-api:
    # completa esta seccion, lee el archivo README en la carpeta movies-api
    container_name: movies-api
    enviroment:
      - BIND_IP
      - BIND_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_SERVER
      - POSTGRES_PORT
    volumes:
      - ./movies-api:/usr/api
      - /usr/app/node_modules
      
    command: - movies-api -b ${BIND_IP} -p ${BIND_PORT}
    depends_on: 
      - postgres 
    
  
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
    expose:
      - ${POSTGRES_PORT}

  flyway:
    image: flyway/flyway:latest
    container_name: migration_flyway
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
      - FLYWAY_GROUP=true
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./sql_migrations:/flyway/sql
    depends_on:
      - postgres
